export class Item {
	id:number;
	itemNumber:number;
    itemType:String;
    itemSubject:String;
    itemOwner:String;
    itemStatus:String;
    itemDescription:String;
    itemCreatedBy:String;
    associatedItem:String;
    itemCreatedDate:Date;
    itemCloseDate:Date;
    applicationName:String;
    priority:number;
    aged:String;
    bounce:number;
    primarySlaBreached:String;
    secondarySlaBreached:String;
    tertirySlaBreached:String;
    resoluation:String
}
